// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thfzgtrktikucekvengk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZnpndHJrdGlrdWNla3ZlbmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzE1MDAsImV4cCI6MjA3NDI0NzUwMH0.pzCssnTjlZy0IM0b3k0QMSgtu1LSgJbKXXekhOaXOCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});